- .gitignore
- README.md
- Vagrantfile
Signed-off-by: Tom Payne <tom@isovalent.com>
> Add quick start example using Vagrant

- bpf/kprobe_pwru.c
- internal/pwru/config.go
- internal/pwru/output.go
- internal/pwru/types.go
> support output netns inode

- bpf/kprobe_pwru.c
- internal/pwru/output.go
- internal/pwru/types.go
support output cpu
Signed-off-by: Leon Huayra <hffilwlqm@gmail.com>
> support output cpu

- Makefile
Run `go generate` and install clang in the container to make the release
target actually work. Also remove generated files as part of the clean
target.
Fixes: ce9cb04ac6ac ("Add minimal Makefile")
> Makefile: fix release target

- .github/dependabot.yml
- .github/workflows/go.yml
- Dockerfile
- Makefile
> Add dependabot config, update Go to 1.18.2

- .github/dependabot.yml
Fixes: 077fd492dbf5 (".github: add dependabot configuration")
> .github: fix label for dependabot PRs

- Dockerfile
#78 
The resultant image size is that of about 80MB.
Signed-off-by: Nikhil Chaudhari nikhil.c@mailbox.org
> add multi-stage builds to minimize docker image size.

- .github/workflows/release.yaml
> gh/workflows: Remove slack notification

- README.md
Also, update the help to accommodate the new --all-kmods.
> Simplify README wrt to debugfs mount

- go.mod
- go.sum
- vendor/github.com/cilium/ebpf/Makefile
- vendor/github.com/cilium/ebpf/README.md
- vendor/github.com/cilium/ebpf/asm/instruction.go
- vendor/github.com/cilium/ebpf/btf/btf.go
- vendor/github.com/cilium/ebpf/btf/btf_types.go
- vendor/github.com/cilium/ebpf/btf/btf_types_string.go
- vendor/github.com/cilium/ebpf/btf/core.go
- vendor/github.com/cilium/ebpf/btf/ext_info.go
- vendor/github.com/cilium/ebpf/btf/marshal.go
- vendor/github.com/cilium/ebpf/btf/strings.go
- vendor/github.com/cilium/ebpf/btf/traversal.go
- vendor/github.com/cilium/ebpf/btf/types.go
- vendor/github.com/cilium/ebpf/collection.go
- vendor/github.com/cilium/ebpf/elf_reader.go
- vendor/github.com/cilium/ebpf/internal/deque.go
- vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
- vendor/github.com/cilium/ebpf/internal/unix/types_other.go
- vendor/github.com/cilium/ebpf/internal/vdso.go
- vendor/github.com/cilium/ebpf/link/kprobe_multi.go
- vendor/github.com/cilium/ebpf/link/link.go
- vendor/github.com/cilium/ebpf/map.go
- vendor/github.com/cilium/ebpf/prog.go
- vendor/github.com/cilium/ebpf/types.go
- vendor/modules.txt
This includes \[1\] which should fix the following error:
Failed to load BTF spec: can't read types: type id 2036: unknown
kind: Unknown (19)
\[1\]: https://github.com/cilium/ebpf/pull/820
cc @shaneutt
Fix #112
> Bump cilium/ebpf to latest

- .gitignore
- README.md
- bpf/kprobe_pwru.c
- internal/pwru/output.go
- internal/pwru/types.go
- internal/pwru/utils.go
- kprobe_shim.go
- main.go
- main_amd64.go
- main_arm64.go
This makes the kprobes loading blazingly fast!
cc @vincentmli
Fix #87
> Add kprobe multi-link support

- internal/pwru/config.go
Previously, when no IPv6 addr was specified, the ICMPv6 filtering was bypassed.
> Fix icmp6 filter

- .github/workflows/release.yaml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- go.mod
Ref. https://cilium.slack.com/archives/C0300URJQM7/p1688374295748359?thread_ts=1688373482.811609&cid=C0300URJQM7
> build, ci: update Go to 1.20

- .github/workflows/test.yml
- Makefile
> Misc build changes

- .github/workflows/test.yml
> Add bpf-next to CI

- .github/workflows/test.yml
- main.go
See commit msgs.
Related https://github.com/cilium/pwru/issues/284.
cc @Asphaltt
> Temporarily fix the EADDRNOTAVAIL when loading

- README.md
Fixes: 5919ba75ae3c ("README.md: adjust kernel config table")
> README.md: fix kernel config table rendering

- .github/workflows/test.yml
> gh/workflows: misc test changes

- .github/actions/pwru-test/action.yaml
> gh/workflows: Upload pwru logs upon failure

- internal/pwru/bpf_prog.go
It is possible to get wrong entry func name of bpf prog when there is info of multiple bpf progs in the BTF.
Instead, get the very first symbol from bpf prog's instructions as its entry func name.
> fix: Get bpf prog entry func name from insns

- internal/asm/x86/x86.go
Otherwise, "pwru --help" might fail it it does not run as root.
> Do not open kcore in init()

- internal/pwru/tracing.go
In `TraceXDP()`, it traces XDP progs by `fentry_xdp` and `fexit_xdp` at the same time.
However, in `tracing.trace()`, it will reset its `links` and `progs`. It should not reset them to support tracing XDP progs by `fentry_xdp` and `fexit_xdp` at the same time.
So, it's better to propagate the target tracing bpf progs to `tracing.trace()` from `TraceXDP()` and `TraceTC()`.
> Fix a minor code logic issue of xdp tracing

- bpf/kprobe_pwru.c
> bpf: Fix broken filter with --filter-trace-xdp

- bpf/kprobe_pwru.c
- internal/pwru/output.go
> Move static variables of big size to percpu array

- renovate.json
To fix the renovate dependency updates.
> renovate: Run go mod tidy

- renovate.json
Suggested-by: André Martins <andre@cilium.io>
> renovate: Try to fix go mod tidy issues

- renovate.json
To fix:
please run 'go mod tidy && go mod vendor', and submit your changes
> renovate: Run go mod vendor

- .github/workflows/renovate-config-validator.yaml
- renovate.json
> renovate: Try go mod vendor/tidy for the group

- .github/workflows/images.yaml
> gh/workflows: Build images per each PR

- .github/workflows/test.yml
Let's see what Friday will bring us.
> Automatically LVH update kernels

- internal/pwru/endbr.go
- internal/pwru/types.go
- main.go
While I was looking at the code, I noticed some small improvements
> cleanup: small code cleanups
