cilium/pwru

internal/pwru/output.go
The initial value of print_skb_id is set to 0. Combined with the fetch
and add, the first event always gets id=0 (also, the one which overflows
u8).
Previously, the outputter was assuming that id=0 means that no str for
printing the skb was allocated which led to the first event not printing
the skb.
Signed-off-by: Martynas Pumputis <m@lambda.lt>
=> Fix printing skb of the first event.

README.md, internal/pwru/types.go, main.go
1. Limit the number of printing to prevent running program from unstopping.
The default number is 1000. The number 0 is for nearly unlimited printing.
2. update README.md
Signed-off-by: Leon Huayra <hffilwlqm@gmail.com>
=> add option --output-limit

bpf/headers/bpf_helper_defs.h, bpf/headers/update.sh
Add an update.sh script which can be used to update the libbpf headers
used by pwru. Pin it to libbpf 0.5.0 which seems to be the closest
matching version. Updating to that version leads to some benign changes
to bpf_helper_defs.h.
This is based on the script in github.com/cilium/ebpf.
=> bpf/headers: add script to update headers from libbpf

README.md, internal/pwru/types.go, internal/pwru/utils.go
Hi all,
Currently `--filter-func=kfree_skb` matches all functions whose name
contains the `"kfree_skb"` string, including `__kfree_skb()`, `kfree_skbmem()`
etc.  To match `kfree_skb()` only, one has to do something like
`--filter-func="^kfree_skb$"`.
This is counterintuitive.  Match the entire string instead in
`GetFuncs()`, so that `--filter-func=kfree_skb` only matches `kfree_skb()`.
To match all function names containing `"kfree_skb"`, one should do
something like `--filter-func=".*kfree_skb.*"` instead.
Thanks,
Signed-off-by: Peilin Ye <peilin.ye@bytedance.com>
=> internal/pwru: Match entire string for --filter-func

bpf/kprobe_pwru.c, internal/pwru/output.go, internal/pwru/types.go
This reverts commit 015a7340a3020963ba0cee4c313655198fb30f6c.
On the 5.16.1-arch1-1 kernel this commit caused the following verifier
error when running "pwru --filter-dst-ip 8.8.8.8 --output-skb":
2022/01/25 12:02:40 Loading objects: field KprobeSkb1:
program kprobe_skb_1: load program: permission denied:
R1 type=ctx expected=fp
; int kprobe_skb_1(struct pt_regs *ctx) {
0: (bf) r9 = r1
; struct sk_buff *skb = (struct sk_buff *) PT_REGS_PARM1(ctx);
1: (79) r8 = *(u64 *)(r9 +112)
2: (b7) r1 = 0
; struct event_t event = {};
3: (63) *(u32 *)(r10 -56) = r1
last_idx 3 first_idx 0
The full log is included in the revert PR.
cc @Asphaltt 
[verifier.log](https://github.com/cilium/pwru/files/7934153/verifier.log)
=> Revert "support output cpu"

KNOWN_ISSUES.md
Add a KNOWN_ISSUE.md to gather the known issues. Now it contains the
first entry which describes the OOM kill issue reported in #45.
Fixes: #45
Signed-off-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>
=> doc: Add a known issue doc with OOM issue description

Dockerfile, Vagrantfile, internal/pwru/types.go, main.go
Following up on this comment https://github.com/cilium/pwru/issues/46#issuecomment-1023213310 adding a new command line argument to set the per CPU buffer. Fixed an issue in the Vagrant setup where llvm-strip is not in $PATH and make fails.
=> Add argument per-cpu-buffer and fix Vagrant setup

go.mod, go.sum, vendor/modules.txt
Release notes: https://github.com/cilium/ebpf/releases/tag/v0.9.0
=> go.mod, vendor: update github.com/cilium/ebpf to v0.9.0

Makefile, main_amd64.go, main_arm64.go
1. Running either `make release` or `make local-release` will cause clang to emit warning messages of type `-Waddress-of-packed-member`. Silence the warnings by explicitly ignoring it.
2. Running `make release` will get error message like `Error: exec: "llvm-strip": executable file not found in $PATH`, fixed by installing `llvm`.
=> Silence clang build warnings and fix Makefile release target

.gitignore, Dockerfile, Makefile
Follow the approach taken in cilium/hubble and cilium/cilium-cli `make release` targets, see cilium/hubble#751 and cilium/cilium-cli#945.
Also update Go and alpine to the most recent versions and add the `release/` directory to `.gitignore`.
=> Run release build as regular user

internal/pwru/types.go, internal/pwru/utils.go, main.go
`pwru` can not runs in the Linux server, whose kernel is built without
`CONFIG_DEBUG_INFO_BTF=y`. But `pwru` can runs with specified kernel BTF
file in such Linux server.
I tried to run `pwru` on Ubuntu 20.04, whose kernel is 5.4 and is built
without `CONFIG_DEBUG_INFO_BTF=y`. Then, I downloaded the kernel BTF
file from github.com/aquasecurity/btfhub, and ran `pwru` with
`--kernel-btf`.
Unfortunately, I waited minutes to exit `pwru`. So I add a progress bar
when exit.
- add option `--kernel-btf`
- print a progress bar while detaching kprobes
Signed-off-by: Leon Hwang <hffilwlqm@gmail.com>
=> Run with specified kernel BTF file

internal/pwru/output.go
On 5.18+ when CONFIG_X86_KERNEL_IBT is set *some* functions gets endbr64 instruction (size 4 bytes) which screws up the kprobe addressing \[1\].
Assume that if no kallsym is found, then it's due to the endbr64.
Tested locally:
$ iptables -t filter -I OUTPUT 1 -m tcp --proto tcp \
--dst 1.1.1.1/32 -j DROP
$ pwru --filter-dst-ip=1.1.1.1 --output-tuple > foo&
$ curl 1.1.1.1
$ cat foo
PROCESS                     FUNC
[curl]             ip_local_out
[curl]           __ip_local_out
[curl]             nf_hook_slow
[curl]         kfree_skb_reason
[curl]   skb_release_head_state
[curl]                tcp_wfree
[curl]         skb_release_data
[curl]             kfree_skbmem
\[1\]: https://lore.kernel.org/bpf/20220811091526.172610-5-jolsa@kernel.org/
Fix #72
=> Try to fix endbr64 kprobe mess

Dockerfile
This updates the Dockerfile to use llvm-13 instead.
Signed-off-by: Jauder Ho <jauderho@users.noreply.github.com>
=> Update Dockerfile to use llvm-14

README.md, internal/pwru/utils.go
It is possible to attach the kprobes only to those functions which are listed in /sys/kernel/debug/tracing/available_filter_functions \[1\].
Previously, we tried to attach the kprobes to all functions. Attaching to a non-listed function failed with ENOENT which was not a problem, as we simply ignored such an error.
However, this becomes a problem with an introduction of the multi-link kprobes mechanism, as any invalid syms makes attachment to all other valid syms to fail.
\[1\]: https://www.kernel.org/doc/Documentation/trace/ftrace.rst
cc @vincentmli 
---
NB: it's non-trivial to fix the K8s example. I'm planning to do `mount -t debugfs none /sys/kernel/debug/` from `pwru`, so that no extra mounts are needed for K8s / Docker.
=> Filter out non-available_filter_functions

README.md
Using the current `Running pwru with Docker` command throws the following error in Ubuntu 22.04/22.10
```
$> docker run --privileged --rm -t --pid=host -v /sys/kernel/debug/tracing:/sys/kernel/debug/tracing cilium/pwru --filter-dst-ip=1.1.1.1
docker: Error response from daemon: error while creating mount source path '/sys/kernel/debug/tracing': mkdir /sys/kernel/debug/tracing: no such file or directory.
```
This is similar to the issue reported here: https://forums.docker.com/t/mount-subpath-of-debugfs/123525
One way to resolve this would be to mount the entire `/sys/kernel/debug` to the `pwru` container.
Similar error is surfaced when applying the Kubernetes spec mentioned in the README. I could get `pwru` running on Kubernetes node only after creating and attaching volume. …
=> Update docker/Kubernetes deployment instructions in README

internal/pwru/types.go, main.go
added flag `--all-kmods` to attach to all available kernel modules.
fix: #100
=> Add flag to attach to all available kernel modules

.github/workflows/go.yml, RELEASE.md
This makes sure CI gets run on pull requests against `main`.
=> Update after renaming to `main` branch

Makefile
Previously, we switched from the git's safe.directory approach to adding host's uid/gid to bypass the git's dubious ownership check.
Unfortunately, this approach started to fail once host uid/gid started to clash with the builder container uids/gids. For example:
docker run \
--rm \
--workdir /pwru \
--volume `pwd`:/pwru docker.io/library/golang:1.18.3-alpine3.16 \
sh -c "apk add --no-cache make git clang llvm && \
addgroup -g 123 release && \
adduser -u 1001 -D -G release release && \
su release -c 'make local-release VERSION=v0.0.7'"
...
addgroup: gid '123' in use
Fix #123
=> make: Use git safe.directory instead of mangling uid/gid

.github/workflows/test.yml, bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/types.go
adding --filter-port to allow filtering or either source or destination port
which helps on debugging bidirectional TCP/UDP flows.
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
=> Add port filter option to allow filtering on either src or dst port

internal/pwru/config.go
Previously, we didn't set the flag for ipv6 when only the src filter was given.
=> Fix IPv6 source filtering

bpf/kprobe_pwru.c, internal/pwru/output.go, internal/pwru/types.go, main.go
This commit extracts a drop reason from kfree_skb_reason(), and prints
it when kfree_skb_reason() is called.
The helper was introduced in the v5.17. The second function param of it
contains a drop reason which is the "skb_drop_reason" enum. To extract
enum, we parse the kernel's BTF, as the enum is not considered as UAPI,
and there were already some position changes among its values.
An example output:
0xffff936378692ce8 6 [curl]             nf_hook_slow 172.20.10.2:33918->1.1.1.1:4240(tcp)
0xffff936378692ce8 6 [curl] kfree_skb_reason(SKB_DROP_REASON_NETFILTER_DROP) 172.20.10.2:33918->1.1.1.1:4240(tcp)
An alternative approach to passing the second param would have been to
set a BPF cookie when attaching the kprobe to the kfree_skb_reason().
However, that would require creating a new …
=> Print drop reason from kfree_skb_reason

bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/types.go, main.go
Since 5.2 kernel, [bpf: implement lookup-free direct value access for maps](https://lore.kernel.org/bpf/20190409210910.32048-2-daniel@iogearbox.net/).
Then, use `bpf2bpf` to reduce .o file size.
Without `bpf2bpf`, the size of .o files:
```bash
-rwxrwx--- 1 root vboxsf 122K Feb  4 13:33 kprobemultipwru_bpfeb.o
-rwxrwx--- 1 root vboxsf 121K Feb  4 13:33 kprobemultipwru_bpfel.o
-rwxrwx--- 1 root vboxsf 117K Feb  4 13:34 kprobemultipwruwithoutoutputskb_bpfeb.o
-rwxrwx--- 1 root vboxsf 116K Feb  4 13:34 kprobemultipwruwithoutoutputskb_bpfel.o
-rwxrwx--- 1 root vboxsf 122K Feb  4 13:33 kprobepwru_bpfeb.o
-rwxrwx--- 1 root vboxsf 121K Feb  4 13:33 kprobepwru_bpfel.o
-rwxrwx--- 1 root vboxsf 117K Feb  4 13:34 kprobepwruwithoutoutputskb_bpfeb.o
-rwxrwx--- 1 root vboxsf 117K Feb  4 13:34 …
```
=> bpf: make config as a constant

internal/pwru/output.go, internal/pwru/types.go
This patch adds "absolute" as a new value to the timestamp flag.
When set, it prefixes each line with the current time.
Closes #149
=> output: add absolute time to timestamp flag

bpf/kprobe_pwru.c
Fix the addr filtering bug caused by `static volatile const struct config CFG`.
Fix #160
=> bpf: Fix addr filtering

Vagrantfile
Ubuntu Impish has become end of life (July 14 2022), causing the Vagrantfile to fail.
This new ubuntu image is an LTS image. It is produced by [generic](https://app.vagrantup.com/generic) and has support for many vagrant providers (e.g. libvirt) while the official ubuntu boxes did not at this time.
=> Updated Vagrantfile to use latest Ubuntu Image

bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/types.go
This PR introduces a bpf map to store matched skb addresses, so for any skb whose address can be found in the map, we see it a matched one without filter check.
This can be useful to observe NAT-ed / encrypted / encapsulated traffic.
Fixes: #84 
=> Track skb by address

main.go, vendor/github.com/cilium/ebpf/rlimit/rlimit.go, vendor/modules.txt
cilium/ebpf provides a helper which removes the memlock limit if necessary. Use it instead of unconditionally bumping RLIMIT_MEMLOCK.
=> main: use rlimit.RemoveMemlock()

libpcap/inject.go
The idea had no flaw but the offset should be 40 instead of -40, or generated ebpf will try to read r10+32 instead of r10-48.
Caught this bug by running examples from "man 7 pcap-filter":
```shell
while read -r expr; do 
echo "$expr"; 
sudo pwru --output-limit-lines 1 "$expr"; 
done <<<"$(man 7 pcap-filter | awk '/EXAMPLES/,/BACKWARD/'  | grep -P '^\s{14}')"
```
Fixes: https://github.com/cilium/pwru/pull/198
=> Fix wrong StackOffset for converting cbpf to ebpf

.github/workflows/test.yml, README.md, bpf/kprobe_pwru.c, docs/vagrant.md, internal/pwru/config.go, internal/pwru/types.go, main.go
This commit allows users to specify the filter pcap in the same way as with tcpdump. For example, `pwru --output-tuple 'host 1.1.1.1 and port 80'`.
=> Drop legacy filter flags

README.md, internal/pwru/types.go, libpcap/compile.go, main.go
1. Delete obsolete perf flag `--perf-cpu-buffer`
2. s/TC_ACT_OK/r0/
=> Minor fixes 

bpf/headers/bpf/bpf_ipv6.h, bpf/kprobe_pwru.c
For some kernel functions like xfrm6_rcv_cb, skb->transport_header is wrongly set to the same value as skb->network_header, causing confusing output showing unexpected tcp port.
This commit lets kprobe_pwru.c:set_tuple() calculate L4 header based on L3 header. The code to calculate ipv6 header length is simply revised from
https://github.com/cilium/cilium/blob/e3a8cfe4ac56883b55cb9f1b8fdfa3ac7f54aaf6/bpf/lib/ipv6.h#L81
Fixes: #205
=> Derive the L4 hdr from the L3 hdr

LICENSE, README.md, bpf/LICENSE.BSD-2-Clause, bpf/LICENSE.GPL-2.0, bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/output.go, internal/pwru/types.go, internal/pwru/utils.go, main.go, tools/getgetter.go, tools/tools.go
It's required as part of the ongoing CNCF donation.
cc @lizrice
=> License userspace with with Apache-2.0, and BPF with Dual BSD-2 and GPL-2.0

.github/workflows/test.yml, Makefile, build.go, local-release.sh
Tested locally by running `make release`.
Fix #212
=> Fix release scripts for arm64

internal/libpcap/inject.go
https://github.com/cilium/pwru/pull/207
cc @jschwinger233
=> Fix code not matching the comment

Makefile
Solves build error:
```
% make
TARGET_GOARCH=amd64 go generate
Generating for amd64
Compiled /tmp/pwru/kprobepwru_bpfel_x86.o
Stripped /tmp/pwru/kprobepwru_bpfel_x86.o
Wrote /tmp/pwru/kprobepwru_bpfel_x86.go
Compiled /tmp/pwru/kprobemultipwru_bpfel_x86.o
Stripped /tmp/pwru/kprobemultipwru_bpfel_x86.o
Wrote /tmp/pwru/kprobemultipwru_bpfel_x86.go
Compiled /tmp/pwru/kprobepwruwithoutoutputskb_bpfel_x86.o
Stripped /tmp/pwru/kprobepwruwithoutoutputskb_bpfel_x86.o
Wrote /tmp/pwru/kprobepwruwithoutoutputskb_bpfel_x86.go
Compiled /tmp/pwru/kprobemultipwruwithoutoutputskb_bpfel_x86.o
Stripped /tmp/pwru/kprobemultipwruwithoutoutputskb_bpfel_x86.o
Wrote /tmp/pwru/kprobemultipwruwithoutoutputskb_bpfel_x86.go
Wrote kprobemultipwru_bpfel_x86_getter.go
Wrote …
```
=> fix: don't compile libpcap RDMA support

main.go
Previous limit 4096 isn't enough for `--all-kmods`, lsof shows pwru uses as many as 5269 fds in that case.
Siged-off-by: Zhichuan Liang <gray.liang@isovalent.com>
=> Raise rlimit nofile to 8192

bpf/kprobe_pwru.c, internal/libpcap/compile.go, internal/libpcap/inject.go, internal/pwru/types.go, main.go
`--filter-track-skb` has a problem of mismatching skbs with same pointer address. This PR tries to fix it by stopping tracking after an skb ends its lifetime.
In general, an skb has 3 possible endings:
1. consumed locally
2. dropped locally
3. transferred via a netdev
All the three endings hit `kfree_skbmem` eventually, so we delete tracked skb pointer address from bpf map at that time.
Fixes: https://github.com/cilium/pwru/pull/194
=> Stop tracking skb in the end of its lifetime

Makefile
libpcap.a built with LLVM 13 produces the following \[1\]:
Failed to inject filter ebpf for kprobe_skb_2: register r8 used twice
\[1\]: https://github.com/cilium/pwru/issues/245#issuecomment-1706155960
=> make: Use LLVM 15 for release builds

.github/workflows/test.yml
To avoid situations like https://github.com/cilium/pwru/issues/245.
Fix #246
=> gh/workflows: Use "make release" to build pwru for testing

README.md
Doing `apply`, `logs`, `delete` in sequence as fast as a script does has the unfortuante effect that it does logs before the pod is ready.
Adding a `wait` sorts that.
Sending `ctrl+c` to break `logs` will however terminate `bash` before `delete` can run.
Putting `delete` in a `trap` sorts that.
=> Allow example to run as script

bpf/kprobe_pwru.c, build.go, internal/libpcap/compile.go, internal/libpcap/inject.go
By using bpf2bpf:
1. We don't have to search for registers holding skb->data and skb-data_end, because they must be at R4 and R5 as arguments.
2. We no longer need a bpf_printk() to be replaced, so pwru developers can use printk for debugging again.
3. We don't need to assume clang behavior or rely on specific clang version.
4. We can delete a lot of code to simplify logic.
=> Use bpf2bpf to simplify injection

bpf/kprobe_pwru.c, internal/libpcap/compile.go, internal/libpcap/inject.go, main.go
Fixes: https://github.com/cilium/pwru/issues/233
=> Support L2 filters such as ARP

.github/workflows/test.yml, internal/libpcap/compile.go, internal/libpcap/inject.go
=> Minor improvements for L2 pcap filters

.github/workflows/test.yml, README.md, bpf/kprobe_pwru.c, go.mod, go.sum, internal/pwru/config.go, internal/pwru/types.go, main.go, vendor/github.com/vishvananda/netns/.golangci.yml, vendor/github.com/vishvananda/netns/LICENSE, vendor/github.com/vishvananda/netns/README.md, vendor/github.com/vishvananda/netns/doc.go, vendor/github.com/vishvananda/netns/netns_linux.go, vendor/github.com/vishvananda/netns/netns_others.go, vendor/github.com/vishvananda/netns/nshandle_linux.go, vendor/github.com/vishvananda/netns/nshandle_others.go, vendor/modules.txt
Set this flag to filter skb from/to the specific interface under the specific netns. If flag --filter-netns is not set, pwru uses current netns.
=> Add --filter-ifname

internal/pwru/output.go
Currently, the proto field (corresponding to skb->protocol which is in network byte order) is reported in pwru's output in network byte order. Report it in host byte order instead so it can easily be matched to the ethertype.
Reported by @darox ref. https://cilium.slack.com/archives/C0300URJQM7/p1695985654194089
=> Report skb->protocol in host byte order

README.md
This commit improves the instructions for building pwru by listing additional tools that are required to build it. Besides that it adds a step for building the libpcap.
=> Readme: Improve instructions

bpf/kprobe_pwru.c, internal/pwru/bpf_prog.go, internal/pwru/output.go, internal/pwru/types.go, main.go
This PR supports tracing tc-bpf as discussion in #239 .
Its running result likes:
```bash
2023/10/21 15:22:05 Attaching kprobes (via kprobe-multi)...
1 / 1 [------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
2023/10/21 15:22:05 Attached (ignored 0)
2023/10/21 15:22:05 Listening for events..
SKB    CPU          PROCESS                     FUNC
0xffff940944c67900      3        [<empty>]                    dummy netns=4026531840 mark=0x0 iface=2(enp0s1) proto=0x0800 mtu=1500 len=98 192.168.64.1:0->192.168.64.2:0(icmp)
0xffff940944c67c00      3           [pwru]                    dummy netns=4026531840 mark=0x0 iface=2(enp0s1) proto=0x0800 mtu=1500 len=98 192.168.64.1:0->192.168.64.2:0(icmp)
0xffff940944c67e00      3 …
```
=> Support tracing tc-bpf

bpf/kprobe_pwru.c, internal/pwru/utils.go, main.go
=> Support tracking skb clones

bpf/kprobe_pwru.c, internal/pwru/output.go
Previously we use tid to find process, leading to misleading output under some situations. 
According to documentation, `bpf_get_current_pid_tgid` returns `current->tgid << 32 | current->pid`. Kernel's view of the PID in user space is usually presented as the thread ID, and kernel's tgid in user space is seen as PID.
=> Find process using pid instead of tid

Makefile
Minor clean-ups from taking a quick look at the Makefile:
- Makefile: Fix awk command in "make help"
- Makefile: Remove compiler versions for "make local-release"
=> Makefile clean-up

README.md, internal/pwru/types.go, main.go
With `./pwru --help` or `./pwru -h`, pwru:
1. displays the help message,
2. prints `pflag: help requested`,
3. exits with error code 2.
Steps 2 and 3 are not expected, the interactive help should return 0 without displaying an error message. This is because of how `pflags.ParseAll()` works. From [its documentation][doc]: _The return value will be ErrHelp if -help was set but not defined._
Let's implement a dedicated function for displaying the help message (reusing `pflags.Usage()` and what we had in pwru already), and call it when users pass `--help` or `-h` to avoid this error and non-zero return value.
[doc]: https://pkg.go.dev/github.com/spf13/pflag#FlagSet.ParseAll
=> internal/pwru: Implement a proper help function

bpf/kprobe_pwru.c, internal/pwru/config.go
The option setting it was superseded by --timestamp=relative and is thus unused since commit 93fee0ade78d ("Make timestamp optional").
=> Remove unused relative timestamp config option

internal/pwru/utils.go, main.go
/sys/kernel/debug/tracing/available_filter_functions is crucial for kprobe-multi but not necessary for kprobe, while pwru refuses to work without it.
This PR let pwru fallback to kprobe backend if /sys/kernel/debug/tracing/available_filter_functions is not available.
=> Let pwru work without /sys/kernel/debug/tracing/available_filter_functions

README.md
After #309, CONFIG_FUNCTION_TRACER is only needed when using the kprobe-backend. Document this in the kernel config table and restructure it a bit while at it.
=> README.md: adjust kernel config table

actions/pwru-log/action.yaml, actions/pwru-run/action.yaml
Other action running K8s can simply deploy PWRU and retrieve logs by:
```
uses: cilium/pwru/actions/pwru-run
with:
pwru-flags: --output-meta --output-tuple --filter-track-skb
pwru-pcap-filter: dst host 1.1.1.1 and dst port 53 and udp
nodename: kind-worker # optional
...
uses: cilium/pwru/actions/pwru-log
if: ${{ !success() }}
with:
testname: ${{ join(matrix.*, ',') }}
```
Example of pwru in pod: https://github.com/cilium/cilium/actions/runs/7408235602/job/20156042287
Example of pwru in daemonset: https://github.com/cilium/cilium/actions/runs/7407859278/job/20154878741
=> Add actions: pwru-run, pwru-log

.github/workflows/test.yml, internal/pwru/ksym.go, main.go
Fix #284 
If we do kprobe.multi, kprobe on functions' addresses instead of symbols.
=> Do kprobe.multi on addresses instead of symbols

README.md, go.mod, internal/pwru/kprobe.go, internal/pwru/output.go, internal/pwru/types.go, main.go
Fix #274 
In order to accelerate attaching/detaching kprobes, do attach/detach kprobes concurrently. By concurrent way, it's a little faster than original way.
On my 6 CPU cores VM,
run by concurrent way:
```
2023/10/25 14:16:03 Attaching kprobes (via kprobe)...
1462 / 1462 [----------------------------------------------------------------------------------------------------] 100.00% 342 p/s
2023/10/25 14:16:07 Attached (ignored 0)
2023/10/25 14:16:07 Listening for events..
SKB    CPU          PROCESS                     FUNC
^C2023/10/25 14:16:08 Received signal, exiting program..
2023/10/25 14:16:08 Detaching kprobes...
1462 / 1462 [-----------------------------------------------------------------------------------------------------] 100.00% 35 p/s
```
run by original way:
```
2023/10/25 …
```
=> Accelerate attaching/detaching kprobes

bpf/kprobe_pwru.c, internal/pwru/bpf_prog.go, internal/pwru/ksym.go, internal/pwru/output.go, main.go
Fix #293 .
`bpf_get_func_ip()` is supported since 5.15 kernel.
- [bpf: Add bpf_get_func_ip helper for tracing programs](https://github.com/torvalds/linux/commit/9b99edcae5c80c8fb9f8e7149bae528c9e610a72)
As a result, we have to figure out a way to avoid `bpf_get_func_ip()`.
Then, I realise that something in `/proc/kallsyms` may help.
```bash
ffffffffc0024020 t bpf_prog_a04f5eef06a7f555_dummy	[bpf]
ffffffffc0024094 t bpf_prog_a04f5eef06a7f555_dummy	[bpf]
ffffffffc002ac4c t bpf_prog_0b3a2ce7164b50f3_fentry_tc	[bpf]
ffffffffc002add0 t bpf_prog_0ca2b1941f84fe9b_fexit_tc	[bpf]
```
Next, read the kernel source code.
- [bpf_prog_ksym_set_name()](https://github.com/torvalds/linux/blob/v5.8/kernel/bpf/core.c#L539)
So, the bpf prog info in `/proc/kallsyms` maybe formats with `ADDR t …
=> Fix get_func_ip for --filter-trace-tc

build.go
Apache-2 has been used by all modules in the project.
Related: https://github.com/cilium/pwru/pull/190
=> Change license of build.go to Apache-2

internal/pwru/kprobe.go, main.go
Fix the case that the detaching progress bar does not show when --output-limit-lines.
=> chore: Show detaching progress always

internal/pwru/bpf_prog.go, internal/pwru/tc_tracer.go
When there are many tc-bpf progs to trace, it'll be very slow to attach tracing one by one.
At this commit, I change the attaching way from serial to concurrent in order to accelerate the attaching progress for tracing tc-bpf progs.
=> Attach tracing of tc-bpf concurrently

internal/pwru/output.go, internal/pwru/types.go, main.go
This commit adds a command line flag that enables
outputting pwru events in json format.
=> Output: Add json output

bpf/kprobe_pwru.c, internal/pwru/output.go
After we consume all of the print_skb_map slot, we start to reuse the slot. On the reused buffer, there's a previous skb string and we don't clear that. So, when the new skb string is shorter than the previous one, we print the garvage string. Keep the length of the string in the map and truncate unnecessary part from the output to avoid it.
=> Avoid printing garvage skb written by previous writer

README.md, bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/types.go, main.go
This PR adds `--filter-track-skb-by-stackid` so we can track traffic even the skb is kfreed and re-built, which frequently happens when traffic is going through bridge. This is more powerful than `--filter-track-skb` on the scenario of encryption + encapsulation.
This PR also paves the way for "tailcall tracing" which relies on stack unwinding. I find it valuable to make stack unwinding a general feature so this is it.
An skb can have different stacks during its lifetime, this PR tries to handle it carefully by comparing `old_stackid` with `stackid` and updating the bpf map in time.
=> Implement --filter-track-skb-by-stackid

README.md, bpf/kprobe_pwru.c, internal/pwru/types.go, main.go
By enabling --filter-track-skb-by-stackid, we can track kernel functions without skb parameter. 
For example, to observe xfrm state lookup, we can use command: `pwru --filter-non-skb-funcs xfrm_state_look_at,xfrm_state_lookup,xfrm_state_lookup_byaddr,xfrm_state_lookup_byspi`. 
Also, this is another step towards "tailcall tracing". This PR allows us to attach bpf helpers (that are probably not skb functions). By fetching bpf helpers' caller pc and converting pc into symbol, we'll see the bpf prog name.
=> Implement --filter-non-skb-funcs

bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/output.go, internal/pwru/tc_tracer.go, internal/pwru/types.go, main.go
struct skb_shared_info is a structure that primarily used by GSO/GRO to store metadata. It is useful to track the behavior of the segmentation offload behavior.
Example output:
```
0xffff985c8384bb00      5 [irq/215-iwlwifi:queue_7:458]        validate_xmit_skb
(struct skb_shared_info){
.gso_segs = (short unsigned int)1,
.gso_type = (unsigned int)1,
.dataref = (atomic_t){
.counter = (int)65538,
},
}
```
=> Add support for printing skb_shared_info

.github/workflows/test.yml, internal/pwru/output.go
The output of `pwru --output-meta --output-tuple` now is like:
```
SKB                CPU PROCESS          NETNS      MARK          IFACE       PROTO  MTU   LEN   TUPLE FUNC
0xffff9fc1014a8700 0   ~/ampdaemon:4417          0 00000000        0         0x0000 0     76    0.0.0.0:0->1.0.0.0:0()                        netlink_broadcast
0xffff9fc1014a8700 0   ~/ampdaemon:4417          0 00000000        0         0x0000 0     76    0.0.0.0:0->1.0.0.0:0()                        netlink_trim
0xffff9fc1014a8700 0   ~/ampdaemon:4417          0 00000000        0         0x0000 0     76    0.0.0.0:0->1.0.0.0:0()                        sk_filter_trim_cap
0xffff9fc1014a8700 0   ~/ampdaemon:4417          0 00000000        0         0x0000 0     76    0.0.0.0:0->1.0.0.0:0() …
```
=> Re-arrange output columns

README.md, bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/ksym.go, internal/pwru/output.go, internal/pwru/types.go, main.go
The example output of `pwru --output-caller  --output-meta --output-tuple --filter-track-skb 'dst host 1.1.1.1 and port 80 ' `:
```
SKB                CPU PROCESS          NETNS      MARK/x        IFACE       PROTO  MTU   LEN   TUPLE FUNC CALLER
0xffff918922e634e8 3   ~bin/curl:659155 4026531840 0               0         0x0000 0     60    10.103.80.168:55476->1.1.1.1:80(tcp) ip_local_out __ip_queue_xmit
0xffff918922e634e8 3   ~bin/curl:659155 4026531840 0               0         0x0000 0     60    10.103.80.168:55476->1.1.1.1:80(tcp) __ip_local_out ip_local_out
0xffff918922e634e8 3   ~bin/curl:659155 4026531840 0               0         0x0800 0     60    10.103.80.168:55476->1.1.1.1:80(tcp) nf_hook_slow   __ip_local_out
0xffff918922e634e8 3   ~bin/curl:659155 4026531840 0 …
```
=> Implement pwru --output-caller to print caller function name

internal/pwru/kprobe.go, internal/pwru/skb_tracker.go, main.go
Refactor code of attaching kprobe and attaching skb-tracking kprobe.
Signed-off-by: Leon Hwang <hffilwlqm@gmail.com>
=> Refactor code of main.go

bpf/headers/bpf/bpf_endian.h, bpf/kprobe_pwru.c, internal/libpcap/inject.go, internal/pwru/bpf_prog.go, internal/pwru/kprobe.go, internal/pwru/output.go, internal/pwru/tc_tracer.go, internal/pwru/tracing.go, internal/pwru/types.go, main.go
Fix #239 
Support tracing XDP
Add an option --filter-trace-xdp to trace all XDP progs on host by
fentry-ing on the progs, like the way tracing tc-bpf
https://github.com/Asphaltt/pwru/commit/2347755900fffe100ab9eebaa180bb9f482df6fb.
The diff from tracing tc-bpf:
1. Not support to filter mark.
2. No mark in meta output.
3. No proto in meta output.
4. Not support --output-skb.
Example with `--filter-trace-xdp --filter-trace-tc`:
```bash
./pwru --filter-trace-xdp --filter-trace-tc --output-limit-lines 10 --filter-func 'xxx' --output-meta --output-tuple icmp
2024/03/04 14:26:47 Listening for events..
SKB    CPU          PROCESS                     FUNC
0xffffbb8cc062cc28      7     [<empty>(0)]               dummy(xdp) netns=4026531840 mark=0x0 iface=2(ens33) proto=0x0000 mtu=1500 len=98 …
```
=> Support tracing XDP

bpf/kprobe_pwru.c
According to source code, kernel uses MTU from skb->_skb_refdst. Let pwru collect MTU from there using the same logic.
It requires to cast skb->_skb_refdst to dst_entry*, then fetch dst_metric_raw(dst, RTAX_MTU) and dst->dev->mtu.
With this patch, pwru can output the correct MTU used by OS.
Case 1: Cilium could reduce the route MTU to 1423 inside a pod. This couldn't be detected by pwru until this patch because it only checked link MTU.
Case 2: Xfrm could reduce the route MTU to 1446 in ip_forward(). Pwru must inspect route MTU from skb->_skb_dstref to understand that, this patch makes it happen.
```
// https://elixir.bootlin.com/linux/v6.5/source/net/ipv4/ip_forward.c#L86
// net/ipv4/ip_forward.c
int ip_forward(struct sk_buff *skb)
{
[...]
rt = skb_rtable(skb);
[...]
mtu = …
```
=> Collect MTU from skb->_skb_refdst

bpf/kprobe_pwru.c, internal/pwru/skb_tracker.go, main.go
When XDP is attached to a veth, skbs will be consumed and re-created on that veth. This is done in the function veth_convert_skb_to_xdp_buff():
```
// drivers/net/veth.c
static int veth_convert_skb_to_xdp_buff(struct veth_rq *rq,
struct xdp_buff *xdp,
struct sk_buff **pskb)
{
struct sk_buff *skb = *pskb;
[...]
nskb = build_skb(page_address(page), PAGE_SIZE);
[...]
skb_copy_header(nskb, skb);
[...]
consume_skb(skb);
skb = nskb;
[...]
}
```
This causes problems for pwru --filter-track-skb because of the new skb addresses. I ran into a lot of situations where I lost track of NAT-ed traffic at veth when cilium kind cluster is created by "kind.sh --xdp".
This patch allows pwru to keep track of the new skbs at XDP-attached veth devices.
=> --filter-track-skb can track skbs re-built from veth_convert_skb_to_xdp_buff

bpf/kprobe_pwru.c, internal/pwru/output.go, internal/pwru/types.go
After https://github.com/cilium/pwru/pull/339, skb_addresses map stores skb->head as key, but kprobe prog on veth_convert_skb_to_xdp_buff still lookup map by &skb. This PR makes things right.
Fixes: #391
=> Fix skb tracing on veth

bpf/kprobe_pwru.c, internal/pwru/output.go
Fixes: https://github.com/cilium/pwru/issues/409
=> bpf: Use percpu array to replace __sync_fetch_and_add

bpf/kprobe_pwru.c, internal/pwru/config.go, internal/pwru/output.go, internal/pwru/tracing.go, internal/pwru/types.go, main.go
This PR uses &skb to track skb instead of skb->head to prevent several issues. XDP tracing is also taken care of by introducing a new bpf map `xdp_dhs_skb_heads`.
=> Fix tracking skb

.github/workflows/release.yaml, .github/workflows/test.yml, Dockerfile, Makefile, go.mod
This also fixes Docker build issues.
Suggested-by:  André Martins <andre@cilium.io>
=> Bump Go version to 1.23.1

internal/pwru/bpf_prog.go, internal/pwru/ksym.go, internal/pwru/output.go, internal/pwru/tracing.go
When I want to troubleshoot a network issue with `--filter-trace-tc`, it cannot to get the address of bpf prog.
After fixing `--filter-trace-tc` issue, I find it fails to run with `--filter-trace-xdp` too. So, I fix the broken `--filter-trace-xdp` BTW.
Signed-off-by: Leon Hwang <hffilwlqm@gmail.com>
=> Fix broken --filter-trace-tc and --filter-trace-xdp

bpf/kprobe_pwru.c, internal/pwru/output.go, internal/pwru/types.go
This commit extracts a drop reason from sk_skb_reason_drop(), and prints it when sk_skb_drop_reason() is called.
This function was introduced in kernel v6.11-rc1. At the same time, kfree_skb_reason()   became an inline helper which just calls  sk_skb_reason_drop().
See: https://github.com/torvalds/linux/commit/ba8de796baf4bdc03530774fb284fe3c97875566
Summary of changes:
- bpf: teach kprobe_skb() to capture the 3rd function argument in the event map
-  go: teach getKFreeSKBReasons() to cope with changes to kfree_skb_reason and introduction of sk_skb_reason_drop() in kernel 
-  go: teach getOutFuncName() about sk_skb_reason_drop()
=> Print drop reason from sk_skb_reason_drop. Catch up with kernel 6.11 changes

bpf/kprobe_pwru.c, internal/pwru/kprobe.go
It failed to run `./pwru --filter-track-bpf-helpers --filter-trace-tc --filter-func '.*udp.*' --output-limit-lines 10 icmp`, because `fentry` does not support `PT_REGS_FP(ctx)`.
And, skip doing kprobe on bpf progs when run `--filter-track-bpf-helpers`.
Signed-off-by: Leon Hwang <hffilwlqm@gmail.com>
=> Improve --filter-track-bpf-helpers

README.md
Relying on Clang 1.12 doesn't make sense. Update it to 12.
=> README.md: Update Clang/LLVM dependency to 12

README.md
It's needed for getAvailableFilterFunctions() which is optional.
=> README: Mention that debugfs is optional

Dockerfile, Makefile, local-release.sh
- Closes https://github.com/cilium/pwru/issues/262
Make it possible to build both amd64 and arm64 Docker images. This can be done with:
docker build --platform linux/amd64,linux/arm64 --tag pwru  .
GHA release workflow only handles GH release artifacts, so the out-of-tree CI job or manual process used to publish images on Docker Hub will have to be updated accordingly.
Also, fix the release script used during image build to support cross-compilation of amd64 on arm64 machines.
(Note that a standalone Docker Engine has to be configured with the containerd snapshotter enabled to build multi-arch images. See https://docs.docker.com/engine/storage/containerd/)
=> Dockerfile: build arm64 variants

bpf/kprobe_pwru.c, build.go, internal/pwru/btf.go, internal/pwru/config.go, internal/pwru/kprobe.go, internal/pwru/utils.go, main.go
When call set_skb_btf() or set_shinfo_btf(), these functions are protected by constant CFG.
Then, while loading kprobe_pwru into kernel, if no --output-skb/--output-skb-shared-info, set_skb_btf()/set_shinfo_btf() won't be verified. Next, these unreachable code will be eliminated by verifier.
=> bpf: Remove OUTPUT_SKB&HAS_KPROBE_MULTI macros

bpf/kprobe_pwru.c
For tracing tc-bpf (same for XDP), it is able to get FP from r10 to track skb by stack ID.
@jschwinger233 could you give me a hand to test this PR by `pwru --filter-trace-tc --filter-track-skb-by-stackid`?
=> Fix tracing tc-bpf with --filter-track-skb-by-stackid

internal/pwru/config.go, internal/pwru/output.go, internal/pwru/types.go
To be able to print skb->cb w/o requiring --filter-trace-tc.
=> Add --output-skb-cb

internal/pwru/utils.go, main.go
This commit enables using the kprobe-multi backend for tracing functions in kernel modules by default if supported. Previously that was only possible by specifying the `--backend=kprobe-multi` option.
Fixes #147
=> Enable kprobe-multi for kmods by default

.github/actions/pwru-test/action.yaml, .github/workflows/test.yml
Test logs are in LVH VM, not in host runner. So, copy them to host before fetching.
Fixes: 8d645756612 ("gh/workflows: Upload pwru logs upon failure")
=> gh/workflows: Fix fetching pwru logs

bpf/kprobe_pwru.c, internal/pwru/output.go
Even with --backend kprobe-multi, pwru still uses kprobe for --filter-track-bpf-helpers. This patch makes pwru capable of distinguishing event types in order to adjust addressres for symbol resolution.
Fixes: https://github.com/cilium/pwru/issues/462
=> Events from kprobe.multi have eventTypeKprobeMulti set in .type

main.go
Remove this as according to the ebpf library docs, this has no effect.
=> cleanup: setting LogSize is deprecated/unused.

bpf/kprobe_pwru.c, internal/pwru/output.go, internal/pwru/types.go
It will be helpful to check receiving a RST packet when fail to run `telnet`.
```bash
2024/12/06 14:30:17 Attaching kprobes (via kprobe-multi)...
146 / 146 [------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
2024/12/06 14:30:17 Attached (ignored 0)
2024/12/06 14:30:17 Listening for events..
SKB                CPU PROCESS          NETNS      MARK/x        IFACE       PROTO  MTU   LEN   __sk_buff->cb[]                                          TUPLE FUNC
0xffff91e7c90a98e8 6   <empty>:0        4026531840 0            ens33:2      0x0800 1500  74    [0x00000000,0x00000000,0x00000000,0x00000000,0x00000000] 192.168.241.133:32956->192.168.241.1:8080(tcp:SYN) tcp_wfree
0xffff91e7cf0a3e00 6   <empty>:0 …
```
=> Output TCP flags alongside tuple

.github/actions/pwru-test/action.yaml, .github/workflows/test.yml
Needed when running upcoming BPF/XDP tracing tests.
=> gh/workflows: Set up traffic before running pwru

bpf/kprobe_pwru.c, internal/pwru/tracing.go
Fixes #483 
There're two issue:
One is `BPF_PROG_ADDR` must be set via `spec.Variable`.
Another one is `.bss` map flag must be updated because go-ebpf v0.17.1 set `BPF_F_MMAPABLE` flag to created `.bss` map. As a result, we can reuse `.bss` map.
Here's the test result:
```bash
2025/01/15 15:14:26 Attaching tc-bpf progs...
2025/01/15 15:14:26 Attaching xdp progs...
2025/01/15 15:14:26 Attaching kprobes (via kprobe)...
29 / 29 [--------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
2025/01/15 15:14:26 Attached (ignored 0)
2025/01/15 15:14:26 Listening for events..
SKB                CPU PROCESS          NETNS      MARK/x        IFACE       PROTO  MTU   LEN   __sk_buff->cb[] …
```
=> Fix broken --filter-trace-xdp caused by go-ebpf v0.17.1

.github/actions/pwru-test/action.yaml, .github/workflows/test.yml, actions/pwru-log/action.yaml
Previous version now fails with:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 13aacd865c20de90d75de3b17ebe84f7a17d57d2`
```
=> CI: Fix Failures: Bump LVM action version to latest release.

bpf/kprobe_pwru.c, internal/libpcap/inject.go, internal/pwru/config.go, internal/pwru/output.go, internal/pwru/types.go, main.go
If the flag is enabled, packets that appear to be vxlan encapsulated will have the filtering function applied. Note: Therefore, to avoid getting non-vxlan traffic you will want to apply a general pcap filter on the vxlan udp ports.
As well, the flag --output-tunnel will result in output of vxlan header data (i.e. flag/vin) as well as inner address tuple.
```bash
sudo ./pwru --output-tuple  --filter-func=udp_queue_rcv_skb  'port 8472' --output-tunnel --filter-tunnel-pcap-l3 'port 8080'  --output-tcp-flags
2025/01/27 16:35:45 Attaching kprobes (via kprobe)...
1 / 1 [-----------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s
2025/01/27 16:35:45 Attached (ignored 0)
2025/01/27 …
```
=> Support outputting and filtering by vxlan/geneve tunnel data

bpf/kprobe_pwru.c, internal/pwru/bpf_prog.go, internal/pwru/endbr.go, internal/pwru/ksym.go, internal/pwru/output.go, internal/pwru/tracing.go, main.go
I encountered the following error days ago.
```Go
failed to trace TC progs: failed to trace bpf progs: failed to find address for function pod_XXX of bpf prog SchedCLS(pod_XXX)#108
```
Then, I realize that we have to improve getting func IP when trace bpf progs.
With commit 55bdaac5dea0 ("Fix tracing tc-bpf with --filter-track-skb-by-stackid") and my blog [Debug a tailcall BUG with fentry](https://asphaltt.github.io/post/ebpf-talk-138-debug-tailcall-bug-with-fentry/), I think it's able to get tracee IP when trace bpf progs.
Then, let me introduce our own `get_func_ip()` helper for tracing to get tracee IP.
Next, in 'output.go', it's incorrect to get func name when output in JSON format.
Why not correct func IP in bpf in order to make sure `event.addr` is correct always?
To achieve it, let …
=> Introduce two enhancements for func IP

Makefile, go.mod, test-app/go.mod
To resolve confused Renovate's "go mod tidy" (in the GH build workflow we compare "go mod tidy"'s output against go 1.23.1).
=> go.mod: Bump to 1.24.1

bpf/kprobe_pwru.c
This has been done in set_xdp_tuple(). Before this change, we have:
0xffff8883ab72f800 6   <empty>:0        4026531840 0             eth1:3      0x8100 1500  88    :0->:0()                                vlan_gro_receive :0->:0()
0xffff8883ab72f800 6   <empty>:0        4026531840 0             eth1:3      0x8100 1500  88    :0->:0()                                inet_gro_receive :0->:0()
0xffff8883ab72f800 6   <empty>:0        4026531840 0             eth1:3      0x8100 1500  88    :0->:0()                                skb_defer_rx_timestamp :0->:0()
0xffff8883ab72f800 6   <empty>:0        4026531840 0             eth1:3      0x8100 1500  88    :0->:0()                                get_rps_cpu :0->:0()
0xffff8883ab72f800 6   <empty>:0        4026531840 0             eth1:3 …
=> Support output tuple for 802.1Q

CONTRIBUTING.md, README.md
Moving the developing and contributing sections out of the main README into a separate file like most projects
=> Move Contributing to a separate file

renovate.json
Fixes: 6e999ef8a ("renovate: Try to fix go mod tidy issues")
Fix #554
=> renovate: Fix syntax

.github/workflows/release.yaml
=> ci: release workflow improvements

bpf/kprobe_pwru.c
commit c4a911e ("Replace BPF_PROG_ADDR with get_func_ip()") caused pwru build error on LoongArch [0] because Leon do not have LoongArch to verify the change for LoongArch,so left out LoongArch.
Since LoongArch does not support bpf trampoline, get_func_ip is not going to be called on LoongArch, add a fake ip_offset value for LoongArch in get_func_ip to avoid the build error. We could fix the ip_offset value when LoongArch starts to support bpf trampoline.
[0]: https://github.com/cilium/pwru/issues/559
Suggested-by: Hengqi Chen <hengqi.chen@gmail.com>
=> fix: pwru build error on LoongArch

Dockerfile, Makefile
clang-15 is no longer available on Debian Trixie, which is used to produce releases.
=> Bump clang to 19

.github/workflows/renovate-config-validator.yaml, Makefile, renovate.json5
Let renovate update the Go image version used for building release binaries. Also update to Go 1.25.1 while at it.
=> renovate: update release Go image
